on:
  schedule:
      - cron: "0 * * * *"
  workflow_dispatch:
  
name: adp_update_data

jobs:
  adp_update_data:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.MY_PAT }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v3
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: piggyback, readr, diplyr, tidyr, tidyverse, purrr, cli
        name: Run data update
      - run: |
          source("R/create_data_file.R")
        shell: Rscript
    
    
    
  
